### PR TITLE
README.rst: Add syntax highlighting

### PR DESCRIPTION
**Pull request by msabramo**
Preview at https://github.com/msabramo/setupext-gitversion/blob/patch-1/README.rst

### CODE REVIEW

**Comment by dave-shawley** [comment]
Thanks for the PR but this would break the formatting at https://pypi.python.org/pypi/setupext-gitversion since ``.. code-block::`` is a Sphinx extension of ReST.  They use `docutils` to render the ReST to HTML.  The best approximation that I found is at [http://rst.ninjs.org/](http://rst.ninjs.org/?n=b3d1bb14ab1a5f7b54193f8c20d2919f&theme=nature).

If there are any ReST errors reported by `docutils`, then you end up with a PyPI entry like https://pypi.python.org/pypi/hypermedia :wink:

**Comment by msabramo** [comment]
Actually docutils and PyPI support code-block now too. They didn't used to but they do now. You can test this by merging my branch in your local git repo and then doing `python setup.py register`. 

I also hate how unforgiving PyPI is about reST. In fact, I submitted a PR for it. 

https://bitbucket.org/pypa/pypi/pull-request/60/fix-bb-214-make-rst-rendering-not-fail-for/diff

Maybe if you +1 it, it will get some attention?

**Comment by msabramo** [comment]
Here's an example of a PyPI page with syntax highlighted code-blocks:

https://pypi.python.org/pypi/requests-unixsocket

**Comment by msabramo** [comment]
You could also test this with the test PyPI instance - https://testpypi.python.org/pypi

**Comment by dave-shawley** [comment]
Cool ... learn something new everyday.  Thanks for the PR.

**Pull request merged**
